apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api
data:
  DB_HOST: {{ .Release.Name }}-postgresql
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_DATABASE: {{ .Values.postgresql.auth.database }}
  DB_PORT: "{{ .Values.postgresql.service.port }}"
  JWT_EXPIRES_IN: {{ .Values.api.environment.jwt.expiresIn }}
  CLOUDFLARE_EXPIRES_IN: {{ .Values.api.environment.cloudflare.expiresIn }}
  CORS_ALLOWED_ORIGINS: '{{ .Values.api.environment.cors.allowedOrigins | toJson }}'
