apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
      nodePort: {{ .Values.client.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-client
