apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: NodePort
  ports:
    - name: port
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      nodePort: {{ .Values.api.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-api
