icc:
  image: e
  service:
    port: 3000
    nodePort: 30091
  environment:
    vultr:
      mainNodepoolTag: tag #The tag of the main nodepool that needs to be excluded from scaling
      vkeID: secret #Id of the cluster
      apikey: secret #API key to use for Vultr API calls
  config:
    scalingMargin: 0.95
    removeAfterMinute: 50
    removeBeforeMinute: 55
    minutesBetweenIteration: 5
    defaultMinimumNodesOnNewNodepool: 1
    defaultMaximumNodesOnNewNodepool: 4
    minimumIndexLengthForForecast: 3
