predictionComponent:
  image: prediction-component:1.0
  environment:
    icc:
      maxAttempts: 3
      retryIntervalSeconds: 15
      host: icc
    forecast:
      steps: 12
      frequencyMinutes: 5
      intervalMinutes: 5
    errorCalculation:
      intervalMinutes: 5
      minAge: 1
    database:
      host: metrics-postgresql
      port: 5432
      username: secret
      password: secret
      database: postgresql