apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  VULTR_API_KEY: {{ .Values.icc.environment.vultr.apikey | b64enc }}
  MAIN_NODEPOOL_TAG: {{ .Values.icc.environment.vultr.mainNodepoolTag }}
  VKE_ID: {{ .Values.icc.environment.vultr.vkeID }}

