apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  API_KEY_VULTR: "{{ .Values.icc.environment.vultr.apikey | b64enc }}"
  IGNORED_NODEPOOL_TAGS: "{{ .Values.icc.environment.vultr.ignoredNodepoolTags | toJson | b64enc }}"
  VKE_ID: "{{ .Values.icc.environment.vultr.vkeID | b64enc }}"
