apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 80
      targetPort: {{ .Values.api.service.port }}
  selector:
    app: {{ .Release.Name }}
