apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard
spec:
  type: NodePort
  ports:
    - name: port
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.dashboard.service.nodePort }}
  selector:
    app.kubernetes.io/name: grafana
