apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.client.service.port }}
  selector:
    app: {{ .Release.Name }}-client
