apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage-retain
provisioner: block.csi.vultr.com
parameters:
  type: high_performance
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer