client:
  image:
  service:
    port: 3000 # Port to expose the service on in the cluster
    nodePort: 30080 # Port to expose the service on from outside the cluster

resources: # Resource requests and limits for the client
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 1256Mi
    
hpa: 
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75 # Target utilization of the requested amount of cpu