prometheus:
  server:
    name: prometheus
    persistentVolume:
      enabled: true
      
    tolerations:
      - key: "Managing"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "Managing-node"
                  operator: In
                  values:
                    - "true"
  alertmanager:
    enabled: false

  prometheus-node-exporter:
    enabled: true
    hostRootFsMount:
      enabled: false