metrics:
  service:
    nodePort: 30083

prometheus:
  server:
    name: prometheus
    persistentVolume:
      enabled: false
    emptyDir:
      sizeLimit: ""
    tolerations:
      - key: "Managing"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "Managing-node"
                  operator: In
                  values:
                    - "true"
  alertmanager:
    enabled: false
 