ingress:
  host: example.com # Domain name
  apiService: api # Release name of cms api
  clientService: client # Release name of cms client
  dashboardService: dashboard-grafana # name of cms dashboard service (Releasename-grafana)

nginx-ingress:
  controller:
    enableLatencyMetrics: true
    tolerations:
      - key: "Managing"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "Managing-node"
                  operator: In
                  values:
                    - "true"
  prometheus:
    service:
      create: true
