ingress:
  host: localhost
  apiService: api
  clientService: client
  dashboardService: dashboard-grafana

nginx-ingress:
  controller:
    enableLatencyMetrics: true
    tolerations:
      - key: "Managing"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "Managing-node"
                  operator: In
                  values:
                    - "true"
  prometheus:
    service:
      create: true
