apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-metrics
data:
  DB_HOST: {{ .Values.postgresql.service.name }}
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_DATABASE: {{ .Values.postgresql.auth.database }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password}}
  DB_PORT: "{{ .Values.postgresql.service.port }}"
  CRON_INTERVAL: {{ .Values.metrics.cron.interval}}

